.TH DWMC 1 dwm\-VERSION
.SH NAME
dwmc \- A fork of fsignal to allow for shell based control of dwm
.Sh SYNOPSIS
.B dwmc
.RB [ \-v ]
.SH DESCRIPTION
dwmc is a fork of fsignal[0] to allow for shell based control of dwm.
This can be used in scripts, or in tools like the SXHKD[1].
.SH COMMANDS
cyclelayout,
focusmon,
focusstack,
incnmaster,
incrgaps,
killclient,
pushdown,
pushup,
quit,
setborderpx
setlayout,
setlayoutex,
setmfact,
tag,
tagall,
tagex,
tagmon,
togglebar,
togglefloating
togglefullscr,
togglegaps,
togglescratch,
togglesticky,
toggletag,
toggletagex,
toggleview,
toggleviewex,
view,
viewall,
viewex,
zoom,
.SH USAGE
Here are some usage examples.

dwmc setmfact +0.05

dwmc togglefullscr

dwmc togglescratch 2
.SH SEE ALSO
.BR fsignal (1)
.BR SXHKD (1)
