#!/usr/bin/env sh

signal() {
	xsetroot -name "fsignal:$*"
}

case $# in
1)
	case $1 in
	killclient | pushup | pushdown | tagall | togglebar | togglefloating | togglefullscr | togglegaps | togglesticky | view | viewall | quit | zoom)
		signal $1
		;;
	*)
		echo "Unknown command or missing one argument."
		exit 1
		;;
	esac
	;;
2)
	case $1 in
	view)
		signal $1 ui $2
		;;
	 cyclelayout | focusmon | focusstack | incrgaps | mfact | setborderpx | setlayoutex | setlayoutex | setmfact | tag | tagex | tagmon | togglescratch | toggletagex | toggleviewex | viewex)
		signal $1 i $2
		;;
	setmfact)
		signal $1 f $2
		;;
	*)
		echo "Unknown command or one too many arguments."
		exit 1
		;;
	esac
	;;
*)
	echo "Too many arguments."
	exit 1
	;;
esac
